apiVersion: apps/v1
kind: Deployment
metadata:
  name: trdl-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trdl
  template:
    metadata:
      labels:
        app: trdl
    spec:
      containers:
      - name: trdl
        image: ramikhreim/trdl:dev-${{ github.run_number }}
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: trdl-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: trdl
